### ISSUE TITLE
symbolinspanish

### ISSUE THREAD

**Issue by DanielZendejas** [weih/symbolinenglish#13]
Hi weih, how about adding a column for spanish names on http://weih.github.io/symbolinenglish/ ?

**Comment by weih** [comment]
@DanielZendejas Of course, absolutely,  that would be great. Could you do that?

**Comment by DanielZendejas** [comment]
@weih Sure, I'll work on it in my spare time. When it's ready I'll let you know with a pull request :)

**Comment by weih** [comment]
@DanielZendejas Great :+1:
